attributes:
  metadata:
    # Settings group can be one of "general", "security", "compute", "network",
    # "storage", "logging", "openstack_services" and "other".
    group: 'storage'
  fuel-plugin-manila_text:
    value: 'Set default value'
    label: 'Text field'
    description: 'Description for text field'
    weight: 25
    type: "text"
